"""
健康知识图谱扩展数据 - 100个样例实体和关系

包含更多疾病、症状、药物、食物、运动等健康领域实体
"""
from agent.knowledge.entity_types import EntityType, HealthEntity
from agent.knowledge.relation_types import RelationType, HealthRelation


# ========== 扩展实体数据 ==========

EXTENDED_ENTITIES = [
    # 更多疾病 (20个)
    HealthEntity("支气管炎", EntityType.DISEASE, "支气管炎症性疾病", synonyms=["气管炎"]),
    HealthEntity("肺炎", EntityType.DISEASE, "肺部感染性疾病"),
    HealthEntity("关节炎", EntityType.DISEASE, "关节炎症性疾病", synonyms=["关节痛"]),
    HealthEntity("风湿病", EntityType.DISEASE, "风湿性疾病"),
    HealthEntity("痛风", EntityType.DISEASE, "尿酸代谢异常疾病"),
    HealthEntity("甲状腺疾病", EntityType.DISEASE, "甲状腺功能异常"),
    HealthEntity("哮喘", EntityType.DISEASE, "慢性呼吸道疾病", synonyms=["支气管哮喘"]),
    HealthEntity("偏头痛", EntityType.DISEASE, "反复发作性头痛"),
    HealthEntity("颈椎病", EntityType.DISEASE, "颈椎退行性疾病"),
    HealthEntity("腰椎病", EntityType.DISEASE, "腰椎退行性疾病", synonyms=["腰痛"]),
    HealthEntity("胆结石", EntityType.DISEASE, "胆囊结石疾病"),
    HealthEntity("肾结石", EntityType.DISEASE, "肾脏结石疾病"),
    HealthEntity("便秘", EntityType.DISEASE, "排便困难症状", synonyms=["排便不畅"]),
    HealthEntity("腹泻", EntityType.DISEASE, "腹泻症状"),
    HealthEntity("胃溃疡", EntityType.DISEASE, "胃黏膜溃疡"),
    HealthEntity("十二指肠溃疡", EntityType.DISEASE, "十二指肠溃疡"),
    HealthEntity("脂肪肝", EntityType.DISEASE, "肝脏脂肪堆积"),
    HealthEntity("胃食管反流", EntityType.DISEASE, "胃酸反流疾病", synonyms=["反流性食管炎"]),
    HealthEntity("帕金森病", EntityType.DISEASE, "神经退行性疾病"),
    HealthEntity("阿尔茨海默病", EntityType.DISEASE, "老年痴呆症", synonyms=["老年痴呆"]),
    HealthEntity("青光眼", EntityType.DISEASE, "眼压升高导致的眼病"),
    HealthEntity("白内障", EntityType.DISEASE, "晶状体混浊"),
    HealthEntity("前列腺炎", EntityType.DISEASE, "前列腺炎症"),
    HealthEntity("骨质疏松", EntityType.DISEASE, "骨密度降低疾病"),

    # 更多症状 (20个)
    HealthEntity("鼻塞", EntityType.SYMPTOM, "鼻腔阻塞", synonyms=["鼻子堵"]),
    HealthEntity("流鼻涕", EntityType.SYMPTOM, "鼻腔分泌物增多"),
    HealthEntity("嗓子疼", EntityType.SYMPTOM, "咽喉疼痛", synonyms=["喉咙痛", "咽痛"]),
    HealthEntity("打喷嚏", EntityType.SYMPTOM, "鼻腔反射动作"),
    HealthEntity("肌肉酸痛", EntityType.SYMPTOM, "肌肉疼痛"),
    HealthEntity("关节疼痛", EntityType.SYMPTOM, "关节部位疼痛", synonyms=["关节疼"]),
    HealthEntity("背痛", EntityType.SYMPTOM, "背部疼痛", synonyms=["腰背痛"]),
    HealthEntity("腿痛", EntityType.SYMPTOM, "腿部疼痛"),
    HealthEntity("视力下降", EntityType.SYMPTOM, "视力模糊或减退"),
    HealthEntity("听力下降", EntityType.SYMPTOM, "听力减退", synonyms=["耳聋"]),
    HealthEntity("记忆力减退", EntityType.SYMPTOM, "记忆能力下降"),
    HealthEntity("注意力不集中", EntityType.SYMPTOM, "注意力分散"),
    HealthEntity("情绪低落", EntityType.SYMPTOM, "抑郁情绪", synonyms=["抑郁"]),
    HealthEntity("焦虑", EntityType.SYMPTOM, "焦虑不安情绪"),
    HealthEntity("烦躁", EntityType.SYMPTOM, "情绪烦躁"),
    HealthEntity("口干", EntityType.SYMPTOM, "口腔干燥"),
    HealthEntity("口渴", EntityType.SYMPTOM, "渴望饮水"),
    HealthEntity("多汗", EntityType.SYMPTOM, "出汗过多"),
    HealthEntity("盗汗", EntityType.SYMPTOM, "睡眠时出汗"),
    HealthEntity("皮肤瘙痒", EntityType.SYMPTOM, "皮肤痒感", synonyms=["皮肤痒"]),
    HealthEntity("皮疹", EntityType.SYMPTOM, "皮肤出现疹子"),
    HealthEntity("水肿", EntityType.SYMPTOM, "组织液积聚", synonyms=["浮肿"]),
    HealthEntity("尿频", EntityType.SYMPTOM, "排尿次数增多"),
    HealthEntity("尿急", EntityType.SYMPTOM, "急需排尿感"),

    # 更多药物 (20个)
    HealthEntity("感冒药", EntityType.DRUG, "治疗感冒的药物"),
    HealthEntity("止咳药", EntityType.DRUG, "缓解咳嗽的药物"),
    HealthEntity("退烧药", EntityType.DRUG, "降低体温的药物", synonyms=["退热药"]),
    HealthEntity("止痛片", EntityType.DRUG, "缓解疼痛的药物", synonyms=["止痛药"]),
    HealthEntity("消炎药", EntityType.DRUG, "抗炎症药物"),
    HealthEntity("胃药", EntityType.DRUG, "治疗胃部疾病的药物"),
    HealthEntity("消炎止痛药", EntityType.DRUG, "抗炎镇痛药物", synonyms=["非甾体抗炎药"]),
    HealthEntity("抗过敏药", EntityType.DRUG, "抗过敏药物", synonyms=["过敏药"]),
    HealthEntity("安眠药", EntityType.DRUG, "助眠药物", synonyms=["助眠药"]),
    HealthEntity("抗焦虑药", EntityType.DRUG, "缓解焦虑的药物"),
    HealthEntity("抗抑郁药", EntityType.DRUG, "治疗抑郁症的药物"),
    HealthEntity("利尿剂", EntityType.DRUG, "促进排尿的药物"),
    HealthEntity("降脂药", EntityType.DRUG, "降低血脂的药物", synonyms=["调脂药"]),
    HealthEntity("钙补充剂", EntityType.DRUG, "补充钙质的药物"),
    HealthEntity("铁补充剂", EntityType.DRUG, "补充铁质的药物"),
    HealthEntity("益生菌", EntityType.DRUG, "调节肠道菌群"),
    HealthEntity("中药", EntityType.DRUG, "传统中药"),
    HealthEntity("感冒清热颗粒", EntityType.DRUG, "中成药"),
    HealthEntity("板蓝根", EntityType.DRUG, "中药，清热解毒"),
    HealthEntity("复方丹参片", EntityType.DRUG, "心血管中成药"),
    HealthEntity("六味地黄丸", EntityType.DRUG, "补肾中成药"),
    HealthEntity("藿香正气水", EntityType.DRUG, "中成药，解暑"),
    HealthEntity("眼药水", EntityType.DRUG, "眼部用药"),
    HealthEntity("滴耳液", EntityType.DRUG, "耳部用药"),

    # 更多食物 (20个)
    HealthEntity("小米", EntityType.FOOD, "健康谷物", attributes={"热量": 358}),
    HealthEntity("糙米", EntityType.FOOD, "全谷物", attributes={"热量": 362, "纤维": "丰富"}),
    HealthEntity("全麦面包", EntityType.FOOD, "全谷物面包", attributes={"热量": 246, "纤维": 6}),
    HealthEntity("红薯", EntityType.FOOD, "健康根茎类", attributes={"热量": 86, "纤维": 3}),
    HealthEntity("山药", EntityType.FOOD, "中药食材", attributes={"热量": 56}),
    HealthEntity("南瓜", EntityType.FOOD, "健康蔬菜", attributes={"热量": 26}),
    HealthEntity("胡萝卜", EntityType.FOOD, "富含胡萝卜素", attributes={"热量": 41, "维生素A": "丰富"}),
    HealthEntity("番茄", EntityType.FOOD, "富含番茄红素", attributes={"热量": 18, "维生素C": "丰富"}),
    HealthEntity("黄瓜", EntityType.FOOD, "低热量蔬菜", attributes={"热量": 15}),
    HealthEntity("芹菜", EntityType.FOOD, "降血压蔬菜", attributes={"热量": 14}),
    HealthEntity("白菜", EntityType.FOOD, "常见蔬菜", attributes={"热量": 13}),
    HealthEntity("油菜", EntityType.FOOD, "绿叶蔬菜", attributes={"热量": 15}),
    HealthEntity("茄子", EntityType.FOOD, "紫色蔬菜", attributes={"热量": 21}),
    HealthEntity("蘑菇", EntityType.FOOD, "菌类", attributes={"热量": 22, "蛋白质": 3}),
    HealthEntity("木耳", EntityType.FOOD, "黑木耳", attributes={"热量": 205, "铁": "丰富"}),
    HealthEntity("海带", EntityType.FOOD, "富含碘", attributes={"热量": 12, "碘": "丰富"}),
    HealthEntity("紫菜", EntityType.FOOD, "海藻类", attributes={"热量": 207, "碘": "丰富"}),
    HealthEntity("核桃", EntityType.FOOD, "坚果", attributes={"热量": 654, "Omega-3": "丰富"}),
    HealthEntity("花生", EntityType.FOOD, "坚果", attributes={"热量": 567, "蛋白质": 25}),
    HealthEntity("杏仁", EntityType.FOOD, "坚果", attributes={"热量": 579, "维生素E": "丰富"}),
    HealthEntity("红枣", EntityType.FOOD, "补血食材", attributes={"热量": 281}),
    HealthEntity("桂圆", EntityType.FOOD, "滋补食材", attributes={"热量": 273}),
    HealthEntity("蜂蜜", EntityType.FOOD, "天然甜味剂", attributes={"热量": 321}),
    HealthEntity("绿茶", EntityType.FOOD, "健康饮品", attributes={"热量": 0, "抗氧化": "丰富"}),

    # 更多运动 (15个)
    HealthEntity("健身操", EntityType.EXERCISE, "有氧健身运动", attributes={"强度": "中"}),
    HealthEntity("广场舞", EntityType.EXERCISE, "群体舞蹈运动", attributes={"强度": "低中"}),
    HealthEntity("羽毛球", EntityType.EXERCISE, "球类运动", attributes={"强度": "中高"}),
    HealthEntity("乒乓球", EntityType.EXERCISE, "球类运动", attributes={"强度": "中"}),
    HealthEntity("网球", EntityType.EXERCISE, "球类运动", attributes={"强度": "高"}),
    HealthEntity("篮球", EntityType.EXERCISE, "球类运动", attributes={"强度": "高"}),
    HealthEntity("排球", EntityType.EXERCISE, "球类运动", attributes={"强度": "中高"}),
    HealthEntity("登山", EntityType.EXERCISE, "户外运动", attributes={"强度": "中高"}),
    HealthEntity("爬山", EntityType.EXERCISE, "户外运动", attributes={"强度": "中"}),
    HealthEntity("滑雪", EntityType.EXERCISE, "冬季运动", attributes={"强度": "中高"}),
    HealthEntity("滑冰", EntityType.EXERCISE, "冰上运动", attributes={"强度": "中"}),
    HealthEntity("跳操", EntityType.EXERCISE, "有氧运动", attributes={"强度": "中"}),
    HealthEntity("拉伸运动", EntityType.EXERCISE, "柔韧性训练", attributes={"强度": "低"}),
    HealthEntity("普拉提", EntityType.EXERCISE, "核心训练", attributes={"强度": "中"}),
    HealthEntity("踢毽子", EntityType.EXERCISE, "传统运动", attributes={"强度": "低中"}),

    # 更多营养素 (10个)
    HealthEntity("维生素B", EntityType.NUTRIENT, "B族维生素"),
    HealthEntity("维生素E", EntityType.NUTRIENT, "抗氧化维生素"),
    HealthEntity("叶酸", EntityType.NUTRIENT, "维生素B9"),
    HealthEntity("烟酸", EntityType.NUTRIENT, "维生素B3"),
    HealthEntity("镁", EntityType.NUTRIENT, "矿物质元素"),
    HealthEntity("磷", EntityType.NUTRIENT, "矿物质元素"),
    HealthEntity("硒", EntityType.NUTRIENT, "微量元素"),
    HealthEntity("碘", EntityType.NUTRIENT, "甲状腺相关元素"),
    HealthEntity("叶黄素", EntityType.NUTRIENT, "视力保护成分"),
    HealthEntity("番茄红素", EntityType.NUTRIENT, "抗氧化成分"),
    HealthEntity("抗氧化成分", EntityType.NUTRIENT, "抗氧化物质"),

    # 更多生活习惯 (10个)
    HealthEntity("均衡饮食", EntityType.HABIT, "营养均衡的饮食习惯"),
    HealthEntity("定时进餐", EntityType.HABIT, "按时吃饭的习惯"),
    HealthEntity("适量饮水", EntityType.HABIT, "保持足够水分摄入"),
    HealthEntity("保持心情愉快", EntityType.HABIT, "心理健康习惯"),
    HealthEntity("社交活动", EntityType.HABIT, "社交互动习惯"),
    HealthEntity("阅读", EntityType.HABIT, "智力活动习惯"),
    HealthEntity("听音乐", EntityType.HABIT, "放松习惯"),
    HealthEntity("户外活动", EntityType.HABIT, "户外活动习惯"),
    HealthEntity("午休", EntityType.HABIT, "午间休息习惯"),
    HealthEntity("睡前放松", EntityType.HABIT, "睡前准备习惯"),

    # 更多健康目标 (5个)
    HealthEntity("增强免疫力", EntityType.HEALTH_GOAL, "提高身体抵抗力"),
    HealthEntity("改善记忆力", EntityType.HEALTH_GOAL, "提高记忆能力"),
    HealthEntity("预防疾病", EntityType.HEALTH_GOAL, "疾病预防目标"),
    HealthEntity("延缓衰老", EntityType.HEALTH_GOAL, "抗衰老目标"),
    HealthEntity("提高睡眠质量", EntityType.HEALTH_GOAL, "睡眠改善目标"),

    # 补充缺失的人体部位
    HealthEntity("颈椎", EntityType.BODY_PART, "颈部脊椎"),
    HealthEntity("腰椎", EntityType.BODY_PART, "腰部脊椎"),
]


# ========== 扩展关系数据 ==========

EXTENDED_RELATIONS = [
    # 疾病-症状关系
    HealthRelation("支气管炎", EntityType.DISEASE.value, "具有症状", "咳嗽", EntityType.SYMPTOM.value),
    HealthRelation("支气管炎", EntityType.DISEASE.value, "具有症状", "发热", EntityType.SYMPTOM.value),
    HealthRelation("肺炎", EntityType.DISEASE.value, "具有症状", "发热", EntityType.SYMPTOM.value),
    HealthRelation("肺炎", EntityType.DISEASE.value, "具有症状", "咳嗽", EntityType.SYMPTOM.value),
    HealthRelation("关节炎", EntityType.DISEASE.value, "具有症状", "关节疼痛", EntityType.SYMPTOM.value),
    HealthRelation("痛风", EntityType.DISEASE.value, "具有症状", "关节疼痛", EntityType.SYMPTOM.value),
    HealthRelation("哮喘", EntityType.DISEASE.value, "具有症状", "咳嗽", EntityType.SYMPTOM.value),
    HealthRelation("偏头痛", EntityType.DISEASE.value, "具有症状", "头痛", EntityType.SYMPTOM.value),
    HealthRelation("颈椎病", EntityType.DISEASE.value, "具有症状", "头痛", EntityType.SYMPTOM.value),
    HealthRelation("颈椎病", EntityType.DISEASE.value, "具有症状", "头晕", EntityType.SYMPTOM.value),
    HealthRelation("腰椎病", EntityType.DISEASE.value, "具有症状", "背痛", EntityType.SYMPTOM.value),
    HealthRelation("便秘", EntityType.DISEASE.value, "具有症状", "食欲不振", EntityType.SYMPTOM.value),
    HealthRelation("腹泻", EntityType.DISEASE.value, "具有症状", "恶心", EntityType.SYMPTOM.value),
    HealthRelation("胃溃疡", EntityType.DISEASE.value, "具有症状", "恶心", EntityType.SYMPTOM.value),
    HealthRelation("脂肪肝", EntityType.DISEASE.value, "具有症状", "乏力", EntityType.SYMPTOM.value),
    HealthRelation("帕金森病", EntityType.DISEASE.value, "具有症状", "记忆力减退", EntityType.SYMPTOM.value),
    HealthRelation("青光眼", EntityType.DISEASE.value, "具有症状", "视力下降", EntityType.SYMPTOM.value),
    HealthRelation("骨质疏松", EntityType.DISEASE.value, "具有症状", "关节疼痛", EntityType.SYMPTOM.value),
    HealthRelation("感冒", EntityType.DISEASE.value, "具有症状", "鼻塞", EntityType.SYMPTOM.value),
    HealthRelation("感冒", EntityType.DISEASE.value, "具有症状", "流鼻涕", EntityType.SYMPTOM.value),
    HealthRelation("感冒", EntityType.DISEASE.value, "具有症状", "嗓子疼", EntityType.SYMPTOM.value),
    HealthRelation("感冒", EntityType.DISEASE.value, "具有症状", "打喷嚏", EntityType.SYMPTOM.value),
    HealthRelation("抑郁症", EntityType.DISEASE.value, "具有症状", "情绪低落", EntityType.SYMPTOM.value),
    HealthRelation("抑郁症", EntityType.DISEASE.value, "具有症状", "失眠", EntityType.SYMPTOM.value),

    # 疾病-风险因素关系
    HealthRelation("痛风", EntityType.DISEASE.value, "风险因素", "饮酒过量", EntityType.RISK_FACTOR.value),
    HealthRelation("哮喘", EntityType.DISEASE.value, "风险因素", "吸烟", EntityType.RISK_FACTOR.value),
    HealthRelation("颈椎病", EntityType.DISEASE.value, "风险因素", "久坐", EntityType.RISK_FACTOR.value),
    HealthRelation("腰椎病", EntityType.DISEASE.value, "风险因素", "久坐", EntityType.RISK_FACTOR.value),
    HealthRelation("便秘", EntityType.DISEASE.value, "风险因素", "饮食不规律", EntityType.RISK_FACTOR.value),
    HealthRelation("骨质疏松", EntityType.DISEASE.value, "风险因素", "缺乏运动", EntityType.RISK_FACTOR.value),
    HealthRelation("骨质疏松", EntityType.DISEASE.value, "风险因素", "久坐", EntityType.RISK_FACTOR.value),
    HealthRelation("脂肪肝", EntityType.DISEASE.value, "风险因素", "饮酒过量", EntityType.RISK_FACTOR.value),
    HealthRelation("脂肪肝", EntityType.DISEASE.value, "风险因素", "肥胖", EntityType.DISEASE.value),
    HealthRelation("关节炎", EntityType.DISEASE.value, "风险因素", "肥胖", EntityType.DISEASE.value),

    # 疾病-治疗关系
    HealthRelation("感冒", EntityType.DISEASE.value, "治疗方式", "感冒药", EntityType.DRUG.value),
    HealthRelation("感冒", EntityType.DISEASE.value, "治疗方式", "板蓝根", EntityType.DRUG.value),
    HealthRelation("咳嗽", EntityType.SYMPTOM.value, "治疗方式", "止咳药", EntityType.DRUG.value),
    HealthRelation("发热", EntityType.SYMPTOM.value, "治疗方式", "退烧药", EntityType.DRUG.value),
    HealthRelation("头痛", EntityType.SYMPTOM.value, "治疗方式", "止痛片", EntityType.DRUG.value),
    HealthRelation("失眠症", EntityType.DISEASE.value, "治疗方式", "安眠药", EntityType.DRUG.value),
    HealthRelation("抑郁症", EntityType.DISEASE.value, "治疗方式", "抗抑郁药", EntityType.DRUG.value),
    HealthRelation("胃炎", EntityType.DISEASE.value, "治疗方式", "胃药", EntityType.DRUG.value),
    HealthRelation("胃溃疡", EntityType.DISEASE.value, "治疗方式", "胃药", EntityType.DRUG.value),
    HealthRelation("骨质疏松", EntityType.DISEASE.value, "治疗方式", "钙补充剂", EntityType.DRUG.value),
    HealthRelation("贫血", EntityType.DISEASE.value, "治疗方式", "铁补充剂", EntityType.DRUG.value),
    HealthRelation("便秘", EntityType.DISEASE.value, "治疗方式", "益生菌", EntityType.DRUG.value),
    HealthRelation("冠心病", EntityType.DISEASE.value, "治疗方式", "复方丹参片", EntityType.DRUG.value),
    HealthRelation("青光眼", EntityType.DISEASE.value, "治疗方式", "眼药水", EntityType.DRUG.value),

    # 药物-疾病关系
    HealthRelation("感冒药", EntityType.DRUG.value, "药物用途", "感冒", EntityType.DISEASE.value),
    HealthRelation("止咳药", EntityType.DRUG.value, "药物用途", "咳嗽", EntityType.SYMPTOM.value),
    HealthRelation("退烧药", EntityType.DRUG.value, "药物用途", "发热", EntityType.SYMPTOM.value),
    HealthRelation("止痛片", EntityType.DRUG.value, "药物用途", "头痛", EntityType.SYMPTOM.value),
    HealthRelation("安眠药", EntityType.DRUG.value, "药物用途", "失眠症", EntityType.DISEASE.value),
    HealthRelation("抗抑郁药", EntityType.DRUG.value, "药物用途", "抑郁症", EntityType.DISEASE.value),
    HealthRelation("胃药", EntityType.DRUG.value, "药物用途", "胃炎", EntityType.DISEASE.value),
    HealthRelation("钙补充剂", EntityType.DRUG.value, "药物用途", "骨质疏松", EntityType.DISEASE.value),
    HealthRelation("益生菌", EntityType.DRUG.value, "药物用途", "便秘", EntityType.DISEASE.value),
    HealthRelation("板蓝根", EntityType.DRUG.value, "药物用途", "感冒", EntityType.DISEASE.value),

    # 食物-营养素关系
    HealthRelation("糙米", EntityType.FOOD.value, "富含", "膳食纤维", EntityType.NUTRIENT.value),
    HealthRelation("红薯", EntityType.FOOD.value, "富含", "膳食纤维", EntityType.NUTRIENT.value),
    HealthRelation("胡萝卜", EntityType.FOOD.value, "富含", "维生素A", EntityType.NUTRIENT.value),
    HealthRelation("番茄", EntityType.FOOD.value, "富含", "维生素C", EntityType.NUTRIENT.value),
    HealthRelation("番茄", EntityType.FOOD.value, "富含", "番茄红素", EntityType.NUTRIENT.value),
    HealthRelation("木耳", EntityType.FOOD.value, "富含", "铁", EntityType.NUTRIENT.value),
    HealthRelation("海带", EntityType.FOOD.value, "富含", "碘", EntityType.NUTRIENT.value),
    HealthRelation("紫菜", EntityType.FOOD.value, "富含", "碘", EntityType.NUTRIENT.value),
    HealthRelation("核桃", EntityType.FOOD.value, "富含", "Omega-3", EntityType.NUTRIENT.value),
    HealthRelation("杏仁", EntityType.FOOD.value, "富含", "维生素E", EntityType.NUTRIENT.value),
    HealthRelation("全麦面包", EntityType.FOOD.value, "含有", "膳食纤维", EntityType.NUTRIENT.value),
    HealthRelation("小米", EntityType.FOOD.value, "含有", "维生素B", EntityType.NUTRIENT.value),
    HealthRelation("菠菜", EntityType.FOOD.value, "含有", "叶酸", EntityType.NUTRIENT.value),
    HealthRelation("绿茶", EntityType.FOOD.value, "含有", "抗氧化成分", EntityType.NUTRIENT.value),
    HealthRelation("南瓜", EntityType.FOOD.value, "含有", "维生素A", EntityType.NUTRIENT.value),
    HealthRelation("芹菜", EntityType.FOOD.value, "含有", "钾", EntityType.NUTRIENT.value),
    HealthRelation("蘑菇", EntityType.FOOD.value, "含有", "蛋白质", EntityType.NUTRIENT.value),

    # 食物-疾病关系
    HealthRelation("胡萝卜", EntityType.FOOD.value, "有益于", "视力下降", EntityType.SYMPTOM.value),
    HealthRelation("番茄", EntityType.FOOD.value, "有益于", "心脏", EntityType.BODY_PART.value),
    HealthRelation("芹菜", EntityType.FOOD.value, "有益于", "高血压", EntityType.DISEASE.value),
    HealthRelation("红薯", EntityType.FOOD.value, "有益于", "便秘", EntityType.DISEASE.value),
    HealthRelation("糙米", EntityType.FOOD.value, "有益于", "便秘", EntityType.DISEASE.value),
    HealthRelation("核桃", EntityType.FOOD.value, "有益于", "记忆力减退", EntityType.SYMPTOM.value),
    HealthRelation("红枣", EntityType.FOOD.value, "有益于", "贫血", EntityType.DISEASE.value),
    HealthRelation("木耳", EntityType.FOOD.value, "有益于", "贫血", EntityType.DISEASE.value),
    HealthRelation("海带", EntityType.FOOD.value, "有益于", "甲状腺疾病", EntityType.DISEASE.value),
    HealthRelation("蜂蜜", EntityType.FOOD.value, "有益于", "失眠", EntityType.SYMPTOM.value),
    HealthRelation("绿茶", EntityType.FOOD.value, "有益于", "心脏", EntityType.BODY_PART.value),
    HealthRelation("益生菌", EntityType.DRUG.value, "有益于", "腹泻", EntityType.DISEASE.value),
    HealthRelation("饮酒过量", EntityType.RISK_FACTOR.value, "不利于", "肝脏", EntityType.BODY_PART.value),
    HealthRelation("久坐", EntityType.RISK_FACTOR.value, "不利于", "颈椎", EntityType.BODY_PART.value),
    HealthRelation("久坐", EntityType.RISK_FACTOR.value, "不利于", "腰椎", EntityType.BODY_PART.value),

    # 运动-健康目标关系
    HealthRelation("羽毛球", EntityType.EXERCISE.value, "适合", "减脂瘦身", EntityType.HEALTH_GOAL.value),
    HealthRelation("乒乓球", EntityType.EXERCISE.value, "适合", "保持健康", EntityType.HEALTH_GOAL.value),
    HealthRelation("登山", EntityType.EXERCISE.value, "适合", "减脂瘦身", EntityType.HEALTH_GOAL.value),
    HealthRelation("跳绳", EntityType.EXERCISE.value, "适合", "减脂瘦身", EntityType.HEALTH_GOAL.value),
    HealthRelation("健身操", EntityType.EXERCISE.value, "适合", "减脂瘦身", EntityType.HEALTH_GOAL.value),
    HealthRelation("广场舞", EntityType.EXERCISE.value, "适合", "保持健康", EntityType.HEALTH_GOAL.value),
    HealthRelation("普拉提", EntityType.EXERCISE.value, "适合", "增肌塑形", EntityType.HEALTH_GOAL.value),
    HealthRelation("拉伸运动", EntityType.EXERCISE.value, "适合", "减压放松", EntityType.HEALTH_GOAL.value),
    HealthRelation("游泳", EntityType.EXERCISE.value, "适合", "增强免疫力", EntityType.HEALTH_GOAL.value),
    HealthRelation("跑步", EntityType.EXERCISE.value, "适合", "增强免疫力", EntityType.HEALTH_GOAL.value),

    # 运动-疾病关系
    HealthRelation("游泳", EntityType.EXERCISE.value, "帮助改善", "关节炎", EntityType.DISEASE.value),
    HealthRelation("瑜伽", EntityType.EXERCISE.value, "帮助改善", "颈椎病", EntityType.DISEASE.value),
    HealthRelation("瑜伽", EntityType.EXERCISE.value, "帮助改善", "腰椎病", EntityType.DISEASE.value),
    HealthRelation("拉伸运动", EntityType.EXERCISE.value, "帮助改善", "颈椎病", EntityType.DISEASE.value),
    HealthRelation("拉伸运动", EntityType.EXERCISE.value, "帮助改善", "腰椎病", EntityType.DISEASE.value),
    HealthRelation("游泳", EntityType.EXERCISE.value, "预防", "骨质疏松", EntityType.DISEASE.value),
    HealthRelation("力量训练", EntityType.EXERCISE.value, "预防", "骨质疏松", EntityType.DISEASE.value),
    HealthRelation("登山", EntityType.EXERCISE.value, "有益于", "心脏", EntityType.BODY_PART.value),
    HealthRelation("羽毛球", EntityType.EXERCISE.value, "有益于", "眼睛", EntityType.BODY_PART.value),
    HealthRelation("乒乓球", EntityType.EXERCISE.value, "有益于", "眼睛", EntityType.BODY_PART.value),

    # 习惯-结果关系
    HealthRelation("均衡饮食", EntityType.HABIT.value, "改善", "便秘", EntityType.DISEASE.value),
    HealthRelation("均衡饮食", EntityType.HABIT.value, "改善", "贫血", EntityType.DISEASE.value),
    HealthRelation("定时进餐", EntityType.HABIT.value, "改善", "胃炎", EntityType.DISEASE.value),
    HealthRelation("适量饮水", EntityType.HABIT.value, "改善", "便秘", EntityType.DISEASE.value),
    HealthRelation("适量饮水", EntityType.HABIT.value, "有益于", "肾脏", EntityType.BODY_PART.value),
    HealthRelation("保持心情愉快", EntityType.HABIT.value, "改善", "失眠", EntityType.SYMPTOM.value),
    HealthRelation("保持心情愉快", EntityType.HABIT.value, "改善", "高血压", EntityType.DISEASE.value),
    HealthRelation("社交活动", EntityType.HABIT.value, "改善", "情绪低落", EntityType.SYMPTOM.value),
    HealthRelation("午休", EntityType.HABIT.value, "改善", "乏力", EntityType.SYMPTOM.value),
    HealthRelation("睡前放松", EntityType.HABIT.value, "改善", "失眠", EntityType.SYMPTOM.value),
    HealthRelation("户外活动", EntityType.HABIT.value, "预防", "骨质疏松", EntityType.DISEASE.value),
    HealthRelation("阅读", EntityType.HABIT.value, "改善", "记忆力减退", EntityType.SYMPTOM.value),
    HealthRelation("听音乐", EntityType.HABIT.value, "改善", "焦虑", EntityType.SYMPTOM.value),
    HealthRelation("听音乐", EntityType.HABIT.value, "改善", "失眠", EntityType.SYMPTOM.value),

    # 人体部位关系
    HealthRelation("肺炎", EntityType.DISEASE.value, "影响", "肺部", EntityType.BODY_PART.value),
    HealthRelation("关节炎", EntityType.DISEASE.value, "影响", "骨骼", EntityType.BODY_PART.value),
    HealthRelation("关节炎", EntityType.DISEASE.value, "影响", "肌肉", EntityType.BODY_PART.value),
    HealthRelation("青光眼", EntityType.DISEASE.value, "影响", "眼睛", EntityType.BODY_PART.value),
    HealthRelation("白内障", EntityType.DISEASE.value, "影响", "眼睛", EntityType.BODY_PART.value),
    HealthRelation("颈椎病", EntityType.DISEASE.value, "影响", "颈椎", EntityType.BODY_PART.value),
    HealthRelation("腰椎病", EntityType.DISEASE.value, "影响", "腰椎", EntityType.BODY_PART.value),
    HealthRelation("帕金森病", EntityType.DISEASE.value, "影响", "大脑", EntityType.BODY_PART.value),
    HealthRelation("阿尔茨海默病", EntityType.DISEASE.value, "影响", "大脑", EntityType.BODY_PART.value),
    HealthRelation("骨质疏松", EntityType.DISEASE.value, "影响", "骨骼", EntityType.BODY_PART.value),

    # 预防关系
    HealthRelation("低盐饮食", EntityType.DIET_TYPE.value, "预防", "高血压", EntityType.DISEASE.value),
    HealthRelation("规律作息", EntityType.HABIT.value, "预防", "失眠症", EntityType.DISEASE.value),
    HealthRelation("规律作息", EntityType.HABIT.value, "预防", "高血压", EntityType.DISEASE.value),
    HealthRelation("运动", EntityType.EXERCISE.value, "预防", "关节炎", EntityType.DISEASE.value),
    HealthRelation("运动", EntityType.EXERCISE.value, "预防", "脂肪肝", EntityType.DISEASE.value),
    HealthRelation("均衡饮食", EntityType.HABIT.value, "预防", "肥胖", EntityType.DISEASE.value),
    HealthRelation("均衡饮食", EntityType.HABIT.value, "预防", "糖尿病", EntityType.DISEASE.value),
    HealthRelation("钙补充剂", EntityType.DRUG.value, "预防", "骨质疏松", EntityType.DISEASE.value),
]


# 扩展实体名称到类型的映射
EXTENDED_ENTITY_LABELS = {e.name: e.entity_type.value for e in EXTENDED_ENTITIES}
for e in EXTENDED_ENTITIES:
    for syn in e.synonyms:
        EXTENDED_ENTITY_LABELS[syn] = e.entity_type.value